### ISSUE TITLE
Crosslink sites scores?

### ISSUE THREAD

**Issue by sarahbonnin** [skrakau/PureCLIP#16]
Hi,

I do not find in the documentation what score_CL, score_E, score_B and score_UC mean (in the 7th column of the crosslink sites BED output)?

I'm running PureCLIP version 1.3.1 this way:
pureclip -i clip.bam -bai clip.bam.bai \
        -ibam igg.bam -ibai igg.bam.bai \
        -g genome.fa \
        -o crosslink_sites.bed -or crosslink_regions.bed \
        -nt 8 -ld

My apologies if the info is there and I just missed it!

Thank you

**Comment by MelaniaAbe** [comment]
Hello Sarah,

First, thanks for the email and command.
BTW, can I share my files with you so that you could also see my errors after running this command? 
How can I share with you, there is 7-day share option, where I can put my files for 7-days for you to download, would that be OK with you to download during that 7 days anf=d try the command and advise on the errors?


Thanks,
Melania

----
Melania Abrahamian
Postdoctoral Scholar 
Carla Koehler's Lab
Department of Chemistry and Biochemistry
University of California
Los Angeles, CA 90095-1569


----- Original Message -----

**Comment by sarahbonnin** [comment]
Hi Melania,

Thanks for the quick answer.
I'm wondering what the output means (7th column of the BED file), but it doesn't seem like an error to me. Is this output unexpected?

chr1    10999711        10999712        3       151.615 +       [score_CL=151.615;score_E=244.963;score_B=396.406;score_UC=151.615]
chr1    13386169        13386170        3       6.36187 +       [score_CL=6.36187;score_E=20.3274;score_B=26.152;score_UC=6.36187]


Thanks

**Comment by skrakau** [comment]
Hi both, 

it seems there was some confusing here. @MelaniaAbe I will answer you in ticket #15.  

@sarahbonnin sorry, you are right, this part is still missing in the documentation. In this output column 7 contains different scores. You can have a look here https://github.com/skrakau/PureCLIP/issues/9 or if you need more details [here](http://dx.doi.org/10.17169/refubium-26166) (p. 106-108).

I hope this helps.

**Comment by sarahbonnin** [comment]
Hi @skrakau,

Thank you! I missed the issue where it was explained, it is more clear now.
Would you advise to use any kind of threshold (and which?) for these scores, to select relevant crosslink sites?

Cheers

**Comment by skrakau** [comment]
Hi,

sorry for the late reply. There is no general answer for this, since it highly depends on your specific question and goal, i.e. are you more interested in sensitivity or precision? 
PureCLIP does not just rank all positions, but it models the background and the target signal distributions, aiming to distinguish between artefacts and real target signals. Thus, in general, you do not need to set a threshold. Due to this reason it also calls less sites compared to some other methods. 

I will close this issue now, but you can let me know if you have further questions.
