### ISSUE TITLE
Could I use any bam with different tools as input ?

### ISSUE THREAD

**Issue by gnilihzeux** [skrakau/PureCLIP#6]
As the title says, is there any limits as input of PureCLIP, because I had some bam from BWA. Is there any differences?
By the way, did it matter that I just use 'Read2 reads' from paired-end sequensing as input of BWA/STAR, and then follow your workflow.
Wish your advice.
Thank you for your time.

**Comment by gnilihzeux** [comment]
This seems didn' t work for bam of BWA. I left commands and logs below. Please have a look, and I'll try STAR next.
BWA align process and then delete duplicates with umi-tools
```
# align
bwa aln -t 12 -n 0.06 -q 18 $BWA_INDEX ${uniq_fq}.gz \
     | bwa samse $BWA_INDEX - ${uniq_fq}.gz
# dedup
nohup umi_tools dedup -I $bam -S $bam_dedup -L $log -E $err &
```
PureCLIP call peaks
```
nohup pureclip -i $bam -bai ${bam}.bai -g $BWA_INDEX -nt 10 -o $peak -ibam $input -ibai ${input}.bai &> $log &
```
## ISSUES
I have IP/input as SP3/SP1, SP2/SP1, SP5/SP4, SP6/SP4, where SP3/SP2 are replicates and so of SP5/SP6.
What my problems is there's no results. And SP3/SP1, SP2/SP1, SP5/SP4 processes seem to be truncated but without error message. As SP6/SP4 is still runing now about 5333 minutes.
[log files](https://github.com/gnilihzeux/tmp/tree/master/PureClip)

## session info
pureclip version: 1.2.0
PC system: CentOS release 6.9 (Final)
CPU info: 48  Intel(R) Xeon(R) CPU E5-2650 v4 @ 2.20GHz
RAM info: total 96 G

**Comment by skrakau** [comment]
In general, apart from the different mappings, it should not make a difference for PureCLIP, if you use BWA or STAR, since it just uses read start sites. 
If you have paired-end reads, it would be advisable to use both reads for mapping (just to improve the mapping) and then use R2 (in case of eCLIP data) for the PureCLIP analysis. For this you can either filter the data yourself or use the PureCLIP parameter '-ur' to select which read should be used.

Try to use the parameter '-iv' to select a subset for the parameter learning, this reduces runtime and memory consumption (see documentation).
